# Spanish-speaking countries (ISO 3166-1 alpha-3 codes)
SPANISH_COUNTRIES = {
    "ESP",
    "ARG",
    "BOL",
    "CHL",
    "COL",
    "CRI",
    "CUB",
    "DOM",
    "ECU",
    "SLV",
    "GTM",
    "HND",
    "MEX",
    "NIC",
    "PAN",
    "PRY",
    "PER",
    "URY",
    "VEN",
}

# Spanish keywords commonly found in passports
SPANISH_KEYWORDS = {
    "REPUBLICA",
    "REPÚBLICA",
    "PASAPORTE",
    "CEDULA",
    "CÉDULA",
    "NACIONALIDAD",
    "FECHA",
    "NACIMIENTO",
    "LUGAR",
    "EXPEDICION",
    "EXPEDICIÓN",
    "VENCIMIENTO",
    "DOCUMENTO",
    "IDENTIDAD",
    "COLOMBIANA",
    "PANAMENA",
    "PANAMEÑA",
    "ESPAÑOLA",
    "ARGENTINA",
    "MEXICANA",
    "VENEZOLANA",
    "PERUANA",
    "CHILENA",
    "ECUATORIANA",
    "BOLIVIANA",
    "COSTARRICENSE",
    "CUBANA",
    "DOMINICANA",
    "SALVADOREÑA",
    "GUATEMALTECA",
    "HONDUREÑA",
    "NICARAGÜENSE",
    "PARAGUAYA",
    "URUGUAYA",
}

# Country name to code mappings
COUNTRY_NAME_MAPPINGS = {
    "COLOMBIA": "COL",
    "COLOMBIANA": "COL",
    "REPUBLIC OF COLOMBIA": "COL",
    "PANAMA": "PAN",
    "PANAMENA": "PAN",
    "PANAMEÑA": "PAN",
    "REPUBLIC OF PANAMA": "PAN",
    "ESPAÑA": "ESP",
    "SPAIN": "ESP",
    "ESPAÑOLA": "ESP",
    "KINGDOM OF SPAIN": "ESP",
    "ARGENTINA": "ARG",
    "REPUBLIC OF ARGENTINA": "ARG",
    "MEXICO": "MEX",
    "MEXICANA": "MEX",
    "UNITED MEXICAN STATES": "MEX",
    "VENEZUELA": "VEN",
    "VENEZOLANA": "VEN",
    "REPUBLIC OF VENEZUELA": "VEN",
    "PERU": "PER",
    "PERUANA": "PER",
    "REPUBLIC OF PERU": "PER",
    "CHILE": "CHL",
    "CHILENA": "CHL",
    "REPUBLIC OF CHILE": "CHL",
    "ECUADOR": "ECU",
    "ECUATORIANA": "ECU",
    "REPUBLIC OF ECUADOR": "ECU",
    "BOLIVIA": "BOL",
    "BOLIVIANA": "BOL",
    "COSTA RICA": "CRI",
    "COSTARRICENSE": "CRI",
    "CUBA": "CUB",
    "CUBANA": "CUB",
    "REPUBLIC OF CUBA": "CUB",
}

# Cedula indicators
CEDULA_INDICATORS = [
    "REPÚBLICA DE PANAMÁ",
    "REPUBLICA DE PANAMA",
    "TRIBUNAL ELECTORAL",
    "CÉDULA",
    "CEDULA",
    "CARNÉ DE IDENTIDAD",
    "CARNE DE IDENTIDAD",
    "DOCUMENTO DE IDENTIDAD",
    "PANAMÁ",
    "PANAMA",
]

# Passport indicators
PASSPORT_INDICATORS = [
    "PASSPORT",
    "PASSEPORT",
    "PASAPORTE",
    "REPUBLIC OF",
    "KINGDOM OF",
    "UNITED STATES",
    "CANADA",
    "AUSTRALIA",
    "GERMANY",
    "FRANCE",
    "SPAIN",
    "ITALY",
    "BRAZIL",
    "MEXICO",
    "INDIA",
    "P<",
]

# Place of birth indicators
BIRTH_PLACE_INDICATORS = [
    "PLACE OF BIRTH",
    "BIRTHPLACE",
    "POB",
    "BIRTH PLACE",
    "P.O.B",
    "LUGAR DE NACIMIENTO",
    "LUGAR DE NAC",
    "LUGAR NACIMIENTO",
    "LIEU DE NAISSANCE",
    "LIEU NAISSANCE",
    "JANM STHAN",
    "POB:",
    "BIRTH:",
    "LUGAR DE NAC.:",
]

# Keywords that are commonly found in Panamanian documents
# such as Cedula and Passport.
DOCUMENT_KEYWORDS_ES = [
    "REPÚBLICA",
    "PANAMÁ",
    "DOCUMENTO",
    "IDENTIDAD",
    "TRIBUNAL",
    "ELECTORAL",
    "CARNÉ",
    "PERMANENTE",
    "NOMBRE",
    "USUAL",
    "FECHA",
    "LUGAR",
    "NACIMIENTO",
    "NACIONALIDAD",
    "SEXO",
    "TIPO",
    "SANGRE",
    "EXPEDIDA",
    "EXPIRA",
]

# Forbidden terms that should not
# appear in a place name
FORBIDDEN_TERMS = [
    "ISSUE",
    "EXPIRY",
    "AUTHORITY",
    "SIGNATURE",
    "DATE",
    "PASSPORT",
    "PLACE OF ISSUE",
    "LUGAR DE EXPEDICION",
    "FECHA DE",
    "RTE",
    "DOCUMENT",
    "VALID",
    "HOLDER",
    "TYPE",
    "CODE",
    "NUMBER",
]

# Mapping of Spanish month abbreviations to
# English month abbreviations
SPANISH_TO_ENGLISH_MONTHS = {
    "ENE": "JAN",
    "FEB": "FEB",
    "MAR": "MAR",
    "ABR": "APR",
    "MAY": "MAY",
    "JUN": "JUN",
    "JUL": "JUL",
    "AGO": "AUG",
    "SEP": "SEP",
    "OCT": "OCT",
    "NOV": "NOV",
    "DIC": "DEC",
}

# English months
ENGLISH_MONTHS = [
    "",
    "JAN",
    "FEB",
    "MAR",
    "APR",
    "MAY",
    "JUN",
    "JUL",
    "AUG",
    "SEP",
    "OCT",
    "NOV",
    "DEC",
]
